version: "3.9"

services:
    nginx:
        image: nginx:1.23.3-alpine
        volumes:
          - ../www:/var/www
          - ./nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "80:80"
        depends_on:
            - php
        container_name: realty_nginx

    php:
        build:
            args:
                user: user
                uid: 1000
            context: .
            dockerfile: ./php/Dockerfile
        volumes:
            - ../www:/var/www
            - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
        container_name: realty_php

    db:
        image: mysql:5.7
        restart: always
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: realty
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ../data:/var/lib/mysql/
        container_name: realty_db

